### ISSUE TITLE
PyInstaller error: mgrs.core.MGRSError: Unable to load libmgrs.cp37-win_amd64.pyd

### ISSUE THREAD

**Issue by cpetruzelli** [hobuinc/mgrs#36]
I see other people are using windows and pyinstaller but I have not been able to resolve this issue. I installed mgrs into my venv and I'm trying to use pyinstaller to create an .exe. When I run the exe I get the following error:

mgrs.core.MGRSError: Unable to load libmgrs.cp37-win_amd64.pyd

I am using mgrs v1.4.2 and pyinstaller v4.2. I'm hoping someone has a solution for me. I tried the solution @uetacog proposed in issue #32 with no luck.

**Comment by sss7526** [comment]
I am using python 3.12 on windows and I got the same error using pyinstaller when trying to launch the executable: "mgrs.core.MGRSError: Unable to load libmgrs.cp312-win_amd64.pyd."

I resolved it by adding this flag to the pyinstaller build command: "--add-binary venv\Lib\site-packages\libmgrs.cp312-win_amd64.pyd:."

**Comment by hobu** [comment]
mgrs 1.5.0 was just released that should include new wheels. please test and open a new ticket if there are any issues.
