### ISSUE TITLE
Feature request: UPS coordinates support

### ISSUE THREAD

**Issue by alexamici** [hobuinc/mgrs#44]
From the Pyhton layer it is not possible to access the underlying functions to convert to and from UPS projections.

I'd like to see something along the lines of:

```
class MGRS:
    def UPSToMGRS(self, hemisphere, easting, northing, MGRSPrecision=5):
        ...
    def MGRSToUTM(self, MGRS, encoding="utf-8"):
        ...
```

Thanks fo the great tool!

**Comment by hobu** [comment]
We are [available for consulting](https://hobu.co/access.html) on such topics or I would be happy to merge a PR that implemented it.
